// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: sf/substreams/sink/database/v1/database.proto

package pbdatabase

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TableChange_Operation int32

const (
	TableChange_OPERATION_UNSPECIFIED TableChange_Operation = 0 // Protobuf default should not be used, this is used so that the consume can ensure that the value was actually specified
	TableChange_OPERATION_CREATE      TableChange_Operation = 1
	TableChange_OPERATION_UPDATE      TableChange_Operation = 2
	TableChange_OPERATION_DELETE      TableChange_Operation = 3
	// The upsert might not be supported by all drivers the sink supports,
	// refer to https://github.com/streamingfast/substreams-sink-sql for
	// which drivers support it.
	//
	// At time of writing, the Postgres driver supports was the only one supporting
	// it.
	TableChange_OPERATION_UPSERT TableChange_Operation = 4
	// Delta upsert: field values are deltas to add to existing values.
	// new_value = COALESCE(existing_value, 0) + delta
	// Useful for balance/counter tracking without querying existing values.
	TableChange_OPERATION_DELTA_UPSERT TableChange_Operation = 5
)

// Enum value maps for TableChange_Operation.
var (
	TableChange_Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_CREATE",
		2: "OPERATION_UPDATE",
		3: "OPERATION_DELETE",
		4: "OPERATION_UPSERT",
		5: "OPERATION_DELTA_UPSERT",
	}
	TableChange_Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED":  0,
		"OPERATION_CREATE":       1,
		"OPERATION_UPDATE":       2,
		"OPERATION_DELETE":       3,
		"OPERATION_UPSERT":       4,
		"OPERATION_DELTA_UPSERT": 5,
	}
)

func (x TableChange_Operation) Enum() *TableChange_Operation {
	p := new(TableChange_Operation)
	*p = x
	return p
}

func (x TableChange_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TableChange_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_sf_substreams_sink_database_v1_database_proto_enumTypes[0].Descriptor()
}

func (TableChange_Operation) Type() protoreflect.EnumType {
	return &file_sf_substreams_sink_database_v1_database_proto_enumTypes[0]
}

func (x TableChange_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TableChange_Operation.Descriptor instead.
func (TableChange_Operation) EnumDescriptor() ([]byte, []int) {
	return file_sf_substreams_sink_database_v1_database_proto_rawDescGZIP(), []int{1, 0}
}

type DatabaseChanges struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableChanges  []*TableChange         `protobuf:"bytes,1,rep,name=table_changes,json=tableChanges,proto3" json:"table_changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseChanges) Reset() {
	*x = DatabaseChanges{}
	mi := &file_sf_substreams_sink_database_v1_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseChanges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseChanges) ProtoMessage() {}

func (x *DatabaseChanges) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_sink_database_v1_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseChanges.ProtoReflect.Descriptor instead.
func (*DatabaseChanges) Descriptor() ([]byte, []int) {
	return file_sf_substreams_sink_database_v1_database_proto_rawDescGZIP(), []int{0}
}

func (x *DatabaseChanges) GetTableChanges() []*TableChange {
	if x != nil {
		return x.TableChanges
	}
	return nil
}

type TableChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Table string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	// Types that are valid to be assigned to PrimaryKey:
	//
	//	*TableChange_Pk
	//	*TableChange_CompositePk
	PrimaryKey    isTableChange_PrimaryKey `protobuf_oneof:"primary_key"`
	Ordinal       uint64                   `protobuf:"varint,3,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	Operation     TableChange_Operation    `protobuf:"varint,4,opt,name=operation,proto3,enum=sf.substreams.sink.database.v1.TableChange_Operation" json:"operation,omitempty"`
	Fields        []*Field                 `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableChange) Reset() {
	*x = TableChange{}
	mi := &file_sf_substreams_sink_database_v1_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableChange) ProtoMessage() {}

func (x *TableChange) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_sink_database_v1_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableChange.ProtoReflect.Descriptor instead.
func (*TableChange) Descriptor() ([]byte, []int) {
	return file_sf_substreams_sink_database_v1_database_proto_rawDescGZIP(), []int{1}
}

func (x *TableChange) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *TableChange) GetPrimaryKey() isTableChange_PrimaryKey {
	if x != nil {
		return x.PrimaryKey
	}
	return nil
}

func (x *TableChange) GetPk() string {
	if x != nil {
		if x, ok := x.PrimaryKey.(*TableChange_Pk); ok {
			return x.Pk
		}
	}
	return ""
}

func (x *TableChange) GetCompositePk() *CompositePrimaryKey {
	if x != nil {
		if x, ok := x.PrimaryKey.(*TableChange_CompositePk); ok {
			return x.CompositePk
		}
	}
	return nil
}

func (x *TableChange) GetOrdinal() uint64 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *TableChange) GetOperation() TableChange_Operation {
	if x != nil {
		return x.Operation
	}
	return TableChange_OPERATION_UNSPECIFIED
}

func (x *TableChange) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type isTableChange_PrimaryKey interface {
	isTableChange_PrimaryKey()
}

type TableChange_Pk struct {
	Pk string `protobuf:"bytes,2,opt,name=pk,proto3,oneof"`
}

type TableChange_CompositePk struct {
	CompositePk *CompositePrimaryKey `protobuf:"bytes,6,opt,name=composite_pk,json=compositePk,proto3,oneof"`
}

func (*TableChange_Pk) isTableChange_PrimaryKey() {}

func (*TableChange_CompositePk) isTableChange_PrimaryKey() {}

type CompositePrimaryKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          map[string]string      `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompositePrimaryKey) Reset() {
	*x = CompositePrimaryKey{}
	mi := &file_sf_substreams_sink_database_v1_database_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositePrimaryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositePrimaryKey) ProtoMessage() {}

func (x *CompositePrimaryKey) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_sink_database_v1_database_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositePrimaryKey.ProtoReflect.Descriptor instead.
func (*CompositePrimaryKey) Descriptor() ([]byte, []int) {
	return file_sf_substreams_sink_database_v1_database_proto_rawDescGZIP(), []int{2}
}

func (x *CompositePrimaryKey) GetKeys() map[string]string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NewValue      string                 `protobuf:"bytes,2,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	OldValue      string                 `protobuf:"bytes,3,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_sf_substreams_sink_database_v1_database_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_sink_database_v1_database_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_sf_substreams_sink_database_v1_database_proto_rawDescGZIP(), []int{3}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetNewValue() string {
	if x != nil {
		return x.NewValue
	}
	return ""
}

func (x *Field) GetOldValue() string {
	if x != nil {
		return x.OldValue
	}
	return ""
}

var File_sf_substreams_sink_database_v1_database_proto protoreflect.FileDescriptor

const file_sf_substreams_sink_database_v1_database_proto_rawDesc = "" +
	"\n" +
	"-sf/substreams/sink/database/v1/database.proto\x12\x1esf.substreams.sink.database.v1\"c\n" +
	"\x0fDatabaseChanges\x12P\n" +
	"\rtable_changes\x18\x01 \x03(\v2+.sf.substreams.sink.database.v1.TableChangeR\ftableChanges\"\xe9\x03\n" +
	"\vTableChange\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x10\n" +
	"\x02pk\x18\x02 \x01(\tH\x00R\x02pk\x12X\n" +
	"\fcomposite_pk\x18\x06 \x01(\v23.sf.substreams.sink.database.v1.CompositePrimaryKeyH\x00R\vcompositePk\x12\x18\n" +
	"\aordinal\x18\x03 \x01(\x04R\aordinal\x12S\n" +
	"\toperation\x18\x04 \x01(\x0e25.sf.substreams.sink.database.v1.TableChange.OperationR\toperation\x12=\n" +
	"\x06fields\x18\x05 \x03(\v2%.sf.substreams.sink.database.v1.FieldR\x06fields\"\x9a\x01\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10OPERATION_CREATE\x10\x01\x12\x14\n" +
	"\x10OPERATION_UPDATE\x10\x02\x12\x14\n" +
	"\x10OPERATION_DELETE\x10\x03\x12\x14\n" +
	"\x10OPERATION_UPSERT\x10\x04\x12\x1a\n" +
	"\x16OPERATION_DELTA_UPSERT\x10\x05B\r\n" +
	"\vprimary_key\"\xa1\x01\n" +
	"\x13CompositePrimaryKey\x12Q\n" +
	"\x04keys\x18\x01 \x03(\v2=.sf.substreams.sink.database.v1.CompositePrimaryKey.KeysEntryR\x04keys\x1a7\n" +
	"\tKeysEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tnew_value\x18\x02 \x01(\tR\bnewValue\x12\x1b\n" +
	"\told_value\x18\x03 \x01(\tR\boldValueBhZfgithub.com/streamingfast/substreams-sink-database-changes/pb/sf/substreams/sink/database/v1;pbdatabaseb\x06proto3"

var (
	file_sf_substreams_sink_database_v1_database_proto_rawDescOnce sync.Once
	file_sf_substreams_sink_database_v1_database_proto_rawDescData []byte
)

func file_sf_substreams_sink_database_v1_database_proto_rawDescGZIP() []byte {
	file_sf_substreams_sink_database_v1_database_proto_rawDescOnce.Do(func() {
		file_sf_substreams_sink_database_v1_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_substreams_sink_database_v1_database_proto_rawDesc), len(file_sf_substreams_sink_database_v1_database_proto_rawDesc)))
	})
	return file_sf_substreams_sink_database_v1_database_proto_rawDescData
}

var file_sf_substreams_sink_database_v1_database_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sf_substreams_sink_database_v1_database_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sf_substreams_sink_database_v1_database_proto_goTypes = []any{
	(TableChange_Operation)(0),  // 0: sf.substreams.sink.database.v1.TableChange.Operation
	(*DatabaseChanges)(nil),     // 1: sf.substreams.sink.database.v1.DatabaseChanges
	(*TableChange)(nil),         // 2: sf.substreams.sink.database.v1.TableChange
	(*CompositePrimaryKey)(nil), // 3: sf.substreams.sink.database.v1.CompositePrimaryKey
	(*Field)(nil),               // 4: sf.substreams.sink.database.v1.Field
	nil,                         // 5: sf.substreams.sink.database.v1.CompositePrimaryKey.KeysEntry
}
var file_sf_substreams_sink_database_v1_database_proto_depIdxs = []int32{
	2, // 0: sf.substreams.sink.database.v1.DatabaseChanges.table_changes:type_name -> sf.substreams.sink.database.v1.TableChange
	3, // 1: sf.substreams.sink.database.v1.TableChange.composite_pk:type_name -> sf.substreams.sink.database.v1.CompositePrimaryKey
	0, // 2: sf.substreams.sink.database.v1.TableChange.operation:type_name -> sf.substreams.sink.database.v1.TableChange.Operation
	4, // 3: sf.substreams.sink.database.v1.TableChange.fields:type_name -> sf.substreams.sink.database.v1.Field
	5, // 4: sf.substreams.sink.database.v1.CompositePrimaryKey.keys:type_name -> sf.substreams.sink.database.v1.CompositePrimaryKey.KeysEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sf_substreams_sink_database_v1_database_proto_init() }
func file_sf_substreams_sink_database_v1_database_proto_init() {
	if File_sf_substreams_sink_database_v1_database_proto != nil {
		return
	}
	file_sf_substreams_sink_database_v1_database_proto_msgTypes[1].OneofWrappers = []any{
		(*TableChange_Pk)(nil),
		(*TableChange_CompositePk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_substreams_sink_database_v1_database_proto_rawDesc), len(file_sf_substreams_sink_database_v1_database_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_substreams_sink_database_v1_database_proto_goTypes,
		DependencyIndexes: file_sf_substreams_sink_database_v1_database_proto_depIdxs,
		EnumInfos:         file_sf_substreams_sink_database_v1_database_proto_enumTypes,
		MessageInfos:      file_sf_substreams_sink_database_v1_database_proto_msgTypes,
	}.Build()
	File_sf_substreams_sink_database_v1_database_proto = out.File
	file_sf_substreams_sink_database_v1_database_proto_goTypes = nil
	file_sf_substreams_sink_database_v1_database_proto_depIdxs = nil
}
